name: zad_almuslem
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  icons_launcher: ^3.0.0
  gap: ^3.0.1
  go_router: ^14.8.0
  bot_toast: ^4.1.3
  flutter_svg: ^2.0.17
  shared_preferences:

  i18n_extension: ^13.0.2
  i18n_extension_importer: ^0.0.6

  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.5.1
  # google_sign_in: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.4.4
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/statePage/
    - assets/images/duaPage/
    - assets/images/quranPage/
    - assets/images/khatamPage/
    - assets/images/suraNames/
    - assets/icons/
    - assets/logo/
    - assets/translations/

  fonts:
    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-Black.ttf
        - asset: assets/fonts/Zain-Bold.ttf
        - asset: assets/fonts/Zain-Light.ttf
        - asset: assets/fonts/Zain-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Zain-Black.ttf
  #       - asset: assets/fonts/Zain-Bold.ttf
  #       - asset: assets/fonts/Zain-ExtraLight.ttf
  #       - asset: assets/fonts/Zain-Light.ttf
  #       - asset: assets/fonts/Zain-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
# icons_launcher:
#   image_path: "assets/logo/logo.png" 
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
#     web:
#       enable: true
#       favicon_path: "assets/logo/logo.png"
#     windows:
#       enable: true
#     macos:
#       enable: true
#     linux:
#       enable: true
